BACKENDAPP/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import IndexPage
from .views import PacientesPage,ContactoPage,Quienes_somosPage,PerdisteContraseñaPage,RegistrarsePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPage.as_view(), name="index"),
    path('pacientes', PacientesPage.as_view(), name="pacientes"),
    path("paciente/", include("app_consultorio.urls")),
    path('contacto', ContactoPage.as_view(), name="contacto"),
    path('quienes_somos', Quienes_somosPage.as_view(), name="quienes_somos"),

    path('perdisteContraseña', PerdisteContraseñaPage.as_view(), name="perdisteContraseña"),
    path('registrarse', RegistrarsePage.as_view(), name="registrarse"),

]

app_consultorio/urls.py
from django.contrib import admin
from django.urls import path , include


from .views import (    
    PacienteListView,   
    PacienteDetailView,
    PacienteCreateView,
    PacienteUpdateView,
    PacienteDeleteView,
)

app_name = "paciente"

urlpatterns = [
    path("", PacienteListView.as_view(), name="all"),
    path("create/", PacienteCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", PacienteDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", PacienteUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", PacienteDeleteView.as_view(), name="delete"),

]

# -> a la urls.py del proyecto

# router
from .router import router
urlpatterns += router.urls

app_consultorio/models.py
from django.db import models
from django.db.models import Model

# Create your models here.

class Paciente(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model

    """
    nombre_appellido  =  models.CharField(max_length=100,default="Desconocido")
    direccion  =  models.CharField(max_length=100)
    mail  =  models.EmailField(blank=False,null=False,default="no_email_contact@gmail.com")
    edad  = models.PositiveSmallIntegerField(blank=False,null=False)
    telefono  =  models.CharField(max_length=20)
    peso  = models.FloatField(blank=True, null=True)
    alta_paciente  = models.DateField(auto_now=True)

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
        db_table = "consultorio_del_Dr"


    def __str__(self):
        return f"El Paciente: {self.nombre_appellido}, edad {self.edad}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
    
    # -> paso siguiente -> admin.py

BACKENDAPP/views.py
from django.views.generic import TemplateView

class IndexPage(TemplateView):
    template_name = "index.html"

class PacientesPage(TemplateView):
    template_name = "pacientes.html"

class ContactoPage(TemplateView):
    template_name = "contacto.html"

class Quienes_somosPage(TemplateView):
    template_name = "quienes_somos.html"

class PerdisteContraseñaPage(TemplateView):
    template_name = "perdisteContraseña.html"

class RegistrarsePage(TemplateView):
    template_name = "registrarse.html"

    

app_consultorio/views.py
# Create your views here.


from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Paciente

# Create your views here.


class PacienteBaseView(View):
    template_name = 'paciente.html'
    model = Paciente
    fields = '__all__'
    success_url = reverse_lazy('paciente:all')


class PacienteListView(PacienteBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS paciente
    """

class PacienteDetailView(PacienteBaseView,DetailView):
    template_name = "paciente_detail.html"

class PacienteCreateView(PacienteBaseView,CreateView):
    template_name = "paciente_create.html"
    extra_context = {"tipo": "Crear paciente"}


class PacienteUpdateView(PacienteBaseView,UpdateView):
    template_name = "paciente_create.html"
    extra_context = {"tipo": "Actualizar paciente"}

class PacienteDeleteView(PacienteBaseView,DeleteView):
    template_name = "paciente_delete.html"
    extra_context = {"tipo": "Borrar paciente"}

# -> app_consultorio.urls.py

app_consultorio/templates/paciente.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}

  <body>
    
    <main class="contenedor_main">
      <section class="contacto">
        
        <h2><a href="{% url 'paciente:create' %}">Crear un paciente</a></h2>

        <br>
        <div class="list">
          {% for paciente in paciente_list %}
        
            <legend>Nombre: {{paciente.nombre_appellido}}</legend>
            <ul>
              <li>Direccion : {{paciente.direccion}}</li>
              <li>Mail: {{paciente.mail}}</li>
              <li>Edad : {{paciente.edad}}</li>
              <li>Telefono : {{paciente.telefono}}</li>
              <li>Peso: {{paciente.peso}}</li>
              <li>Alta_paciente : {{paciente.alta_paciente}}</li>
            </ul>
            <br>
              <div>
                  <label for="">Detalles: </label>
                  <a href="{% url 'paciente:detail' paciente.id  %}">🟢</a>
              </div>
              <div>
                  <label for="">Borrar: </label>
                  <a href="{% url 'paciente:delete' paciente.id %}">❌</a>
              </div>
              <div>
                  <label for="">Editar: </label>
                  <a href="{% url 'paciente:update' paciente.id %}">📋</a>
              </div>
              <br>
              <br>
          {% endfor %}
        </div>
      </section>
    </main>
    {% include 'footer_template.html' %}
  </body>
</html>

{% endblock %}

app_consultorio/templates/paciente_create.html
{% extends 'base_template.html' %}
{% block contenido %}

<main>
    <div class="main-color-pacientes">
        <h1>CREAR PACIENTE</h1>
        <form method="post">

            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ tipo }}" />

        </form>

        <a href="{% url 'paciente:all' %}">Volvamos al Inicio</a>
    </div>
</main>
{% endblock %}

app_consultorio/templates/paciente_delete.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}

<main>
  <div>
    <h2>Estas seguro que deseas borrar esta paciente?</h2>
    <h2>{{store.nombre}}</h2>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'paciente:all' %}">Cancelar</a>
  </div>
</main>

{% endblock %}

app_consultorio/templates/paciente_detail.html
{% extends 'base_template.html' %} 
{% block contenido %}

<main>
  <div>
    <h1>{{paciente.nombre_appellido}}</h1>
    {% for label, value in paciente.get_fields %}
    <div>
      <span>{{label | upper}}</span>
      <span> <b> {{value}} </b></span>
    </div>

    {% endfor %}

    <a href="{% url 'paciente:all' %}">Ir al inicio</a>
  </div>
</main>

{% endblock%}

templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static './css/style.css'%}" />
    <link rel="stylesheet" href="{% static './css/header.css'%}" />
    <link rel="stylesheet" href="{% static './css/footer.css'%}" />

    <link rel="stylesheet" href= "{% static './css/maincontacto.css'%}" />
    <link rel="stylesheet" href= "{% static './css/quienessomos.css'%}" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
      rel="stylesheet"
    />

    <!-- FAVICON -->
    <link rel="icon" href="assets/media/iconos/faviconfondo.ico" />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <!-- Iconos de redes -->
    <script
      src="https://kit.fontawesome.com/e30e97780d.js"
      crossorigin="anonymous"
    ></script>
    <title>El consultorio de Victor</title>
  </head>

  <body>
    <header>
      <nav>
        <a class="activo" href="/">Principal</a>
        <a href="{% url 'pacientes' %}">Autogestión</a>
        <a href="{% url 'paciente:all' %}">CRUD pacientes</a>
        <a href="{% url 'contacto' %}">Contacto</a>
        <a href="{% url 'quienes_somos' %}">Quienes Somos</a>
        
      </nav>
      <h1>Bienvenido a su consultorio virtual</h1>
    </header>
    
    {% block contenido %} 
    {% endblock %}

templates/contacto.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}


  <body>
    
    <main class="contenedor_main">
      <section class="contacto">
        <h3>Dejanos tu consulta</h3>
        <p>Nos contactaremos a la brevedad a fin de brindarte una respuesta.</p>
        <form action="" class="form">
          <input type="text" id="inputNombre" placeholder="NOMBRE Y APELLIDO" />
          <input
            type="email"
            name="inputEmail"
            id="inputEmail"
            placeholder="EMAIL"
          />
          <input
            type="text"
            name="inputTelefono"
            id="inputTelefono"
            placeholder="TELEFONO"
          />
          <textarea
            name="consulta"
            id="consulta"
            cols="30"
            rows="8"
            placeholder="Deseo consultar sobre"
          ></textarea>
          <button type="submit">Enviar</button>
        </form>
      </section>
    </main>
    {% include 'footer_template.html' %}
  </body>
</html>

{% endblock %}

templates/dashboard.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administración</title>
    <link rel="stylesheet" href="{% static './css/style.css'%}" />
    <link rel="stylesheet" href="{% static './css/header.css'%}" />
    <link rel="stylesheet" href="{% static './css/footer.css'%}" />
    <link rel="stylesheet" href="{% static '../css/dashboard.css'%}" />

    <!-- Iconos de redes -->
    <script src="https://kit.fontawesome.com/e30e97780d.js" crossorigin="anonymous"></script>

    <!-- FAVICON -->
    <link rel="icon" href="../assets/media/iconos/faviconfondo.ico">
    
    <!-- Formulario --> 
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet"> 
    <!-- Link hacia el archivo de estilos css -->
    <link rel="stylesheet" href="css/login.css">
    <style type="text/css">
    </style>
    <script type="text/javascript">
    </script>
</head>
<body class="pacientes">
    <header>
      <nav>
        <a href="../index.html">Principal</a>
        <a href="./pacientes.html">Autogestión</a>
        <a href="./contacto.html">Contacto</a>
        <a href="./quienes_somos.html">Quienes Somos</a>
      </nav>
      <h1 class="dashboard_h1">Pacientes</h1>
    </header>

    <main>
      <input type="button" value="Consultar datos" id="botonPacientes">
      <div id="datos">
        
      </div>
    </main>
    {% include 'footer_template.html' %}
    <script src="{% static '../js/dashboard.js'%}"></script>
</body>
</html>
{% endblock %}

templates/footer_template.html
{% load static %}

    <footer>
      <section class="barra_inferior">
        <a href="https://www.facebook.com/"><i class="fa-brands fa-facebook-f"></i></a>
        <a href="https://www.instagram.com"><i class="fa-brands fa-instagram"></i></a>
        <a href="https://twitter.com/"><i class="fa-brands fa-x-twitter"></i></a>
        <a href="mailto:example@mail.com"><i class="fa-regular fa-envelope"></i></a>
      </section>
    </footer>

    {% block contenido %} 
    {% endblock %}
    

templates/index.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}


    <main>
      <h1>Bienvenido a su consultorio virtual</h1>
      <br>
      <!-- imagenes para carrusel con animación de CSS -->
      <div class="slider">
        <ul>
          <li>
            <picture>
              <source srcset="./assets/media/imagenes/consultas_movil.jpg" media="(max-width:500px)">
              <img src= "{% static './media/imagenes/Consultas.jpg' %}" alt="">
            </picture>
          </li>
          <li> 
            <picture>
                <source srcset="./assets/media/imagenes/RECURSO_MOVIL.jpg" media="(max-width:500px)">
                <img src= "{% static './media/imagenes/Recurso.jpg' %}" alt="">
                
            </picture>
          </li>
          <li>
            <picture>
            <source srcset="./assets/media/imagenes/Recurso1_movil.jpg" media="(max-width:500px)">
            <img src= "{% static './media/imagenes/recurso1.jpg' %}" alt="">
            
            </picture>
          </li>
        </ul>
      </div>
      <!-- <div class="tablet_animation">
        <img src="assets/media/imagenes/consultas_tablet.jpg" alt="">
      </div> -->
      
      <!-- botones debajo del carrusel-->
      <div class="botones">
        <span><a href="https://www.whatsapp.com/"><img src= "{% static './media/imagenes/celular.png' %}" alt=""></a><p class="botones_texto">Atención<br> telefónica</p></span>
        <span><a href="https://calendly.com/es"><img src= "{% static './media/imagenes/calendario.png' %}" alt=""></a><p class="botones_texto">Central<br> de turnos</p></span>
        <span><a href="https://meet.google.com/"><img src= "{% static './media/imagenes/Notebook.png' %}" alt=""></a><p class="botones_texto">Consulta <br> virtual</p></span>
        <span><a href="./index.html#dondeestamos"><img src="{% static './media/imagenes/ubicacion.png' %}" alt=""></a><p class="botones_texto">Ver <br> ubicación</p></span>
      </div>
      
      <div class="especialidad_container">
        <section class="especialidad">
          <img src= "{% static './media/imagenes/especialidad3.png' %}" alt="">
          <div>
            <h3>Especialidad médica</h3> <br>
            <ul>
              <li>Ginecología - Telemedicina</li>
              <li>Histeroscopía y colposcopía</li>
              <li>Dolor pelviano crónico</li>
              <li>Tratamiento del HPV</li>
            </ul>
            <br>
            <p class="conoce_mas"><a href="./pages/quienes_somos.html"> Conocé más</a></p>
          </div>
        </section>
      </div>  
      <div class="fondo_ubicacion">
        <a name="dondeestamos">Donde estamos</a>
        <!-- <img src="/assets/media/imagenes/ubic_celular.png" alt=""> -->
      </div>

      <section class="map">
        <div><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3404.8699861789796!2d-64.1964236!3d-31.417708!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9432a27e3488a775%3A0xb50ffe1a1cf715e4!2sGral.%20Jose%20Artigas%20395%2C%20C%C3%B3rdoba!5e0!3m2!1ses-419!2sar!4v1696601737964!5m2!1ses-419!2sar" 
        width="100%" height="300px" style="border:0;" allowfullscreen="" loading="lazy" 
        referrerpolicy="no-referrer-when-downgrade">
        </iframe>
        </div>
      </section>

      {% include 'footer_template.html' %}
    </main>

  </body>
</html>

{% endblock %}

templates/pacientes.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}
    
    <main>
    <!-- loguin -->
    <div id="contenedor">
            
      <div id="contenedorcentrado">
          <div id="login">
              <form id="loginform">
                  <label for="usuario"></label>
                  <input id="usuario" type="text" name="usuario" id="usuario" placeholder="Usuario" required>
                  <br>
                  <label for="password"></label>
                  <input id="password" type="password" id="password" placeholder="Contraseña" name="password" required>
                  <br>
                  <button type="submit" title="Ingresar" name="Ingresar" id="Ingresar">Login</button>
              </form> 
          </div>
          <div id="derecho">
              <div class="titulo">
                  Bienvenido
              </div><br>
              <hr>
              <div class="pie-form">
                  <a href="{% url 'perdisteContraseña' %}">Perdiste tu contraseña</a>
                  <a href="{% url 'registrarse' %}">Registrarse</a>
                  <hr><br>
                  <a href="../">Volver</a>
              </div>
          </div>
      </div>
    </div>

    <footer>
        <section class="barra_inferior">
          <a href="https://www.facebook.com/"><i class="fa-brands fa-facebook-f"></i></a>
          <a href="https://www.instagram.com"><i class="fa-brands fa-instagram"></i></a>
          <a href="https://twitter.com/"><i class="fa-brands fa-x-twitter"></i></a>
          <a href="mailto:example@mail.com"><i class="fa-regular fa-envelope"></i></a>
        </section>
      </footer>

    </main>
  <!-- loguin -->

</body>
</html>

{% endblock %}

templates/perdisteContraseña.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}

<body>
  <br><br>
    <h1>Recuperar contraseña</h1>
    <main>
      <div id="contenedor_contr">
        <br>
        <section>
          <form action="" class="form">
            <p>
            <b>Ingrese el correo con el que se ha registrado</b>
            </p>
            <input
              type="email"
              name="inputEmail"
              id="inputEmail"
              placeholder="EMAIL" 
              required
            />
            <button type="submit">Enviar</button>
          
          </form>
        </section>
        
        <br>
        <br>
        <a href="{% url 'pacientes' %}"><i class="fa-solid fa-arrow-left" style="color: #ffffff;"></i> Volver</a>
      </div>

      {% include 'footer_template.html' %}

    </main>

</body>
</html>

{% endblock %}

templates/quienes_somos.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}


    <body>
    <main class="quienes_container">
            <section class="quienes">
              <img src="{% static './media/imagenes/img_cara.jpg' %}" alt="">
              
              <div>
                    <h3>Dr. Víctor Cortéz Pérez</h3>
                    <h3>MP 13888</h3>
                    <h4>Ginecología | Videocolposcopía</h4>
                    <p>Soy médico ginecólogo y cirujano histeroscopista colposcopista con más de 10 años de experiencia.
                    Me especializo en dolor pelviano crónico y en el tratamiento del HPV.
                    Actualmente me desarrollo como profesor universitario en la Universidad Nacional de Córdoba y trabajo en consultorios privados, atendiando presencial y virtualmente. 
                    </p>
              </div>
            </section>

    </main>
    </body>
    {% include 'footer_template.html' %}
</html>

{% endblock %}

templates/registrarse.html
{% extends 'base_template.html' %}
{% load static %}
{% block contenido %}


<body>
  <br><br>
    <h1>Registrarse</h1>
    <main>
        <div id="contenedor_registro">
        <section>
          <form class="form">
            <input
              type="text"
              name="user"
              id="inputUsuario"
              placeholder="Nombre de usuario"
              required
            />
            <br>
            <input
              type="email"
              name="email"
              id="inputEmail"
              placeholder="Correo electrónico"
              pattern="^(\w+[/./-]?){1,}@[a-z]+[/.]\w{2,}$"
              title="Formato de Correo Invalido"
              required
            />
            <br>
            <input
              type="password"
              name="password"
              id="passwordEmail"
              placeholder="Ingrese su contraseña"
              required
            />
            <br>
            <input
            type="password"
            name="passwordConfirm"
            id="passwordConfirm"
            placeholder="Confirme su contraseña"
            required
          />
          <br>
            <button id="buttonEnviar" type="submit">Enviar</button>
          </form>
        </section>
        <br />
        <a href="{% url 'pacientes' %}"><i class="fa-solid fa-arrow-left" style="color: #ffffff;"></i> Volver</a>
      </div>

      {% include 'footer_template.html' %}
      
      </main>

    <script src="{% static '../js/registrarse.js'%}"></script>
    
</body>
</html>
{% endblock %}